modLoader = "javafml"
loaderVersion = "[39,)"
#updateJSONURL=""
issueTrackerURL = "https://github.com/ramidzkh/Applied-Botanics/issues"
displayURL = "https://github.com/ramidzkh/Applied-Botanics#readme"
logoFile = "logo.png"
#credits="Thanks for this example mod goes to Java"
authors = "ramidzkh"
license = "See GitHub repository for details"

[[mods]]
modId = "appbot"
version = "${version}"
displayName = "Applied Botanics"
description = "mana through ae2, what could go wrong"

[[dependencies.appbot]]
modId = "forge"
mandatory = true
versionRange = "[40.0.0,41.0.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appbot]]
modId = "ae2"
mandatory = true
versionRange = "(,12.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.appbot]]
modId = "botania"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
